### ISSUE TITLE
Provide elk command

### ISSUE THREAD

**Issue by lukasmalkmus** [masseelch/elk#17]
Instead of having to create a file locally, it would be awesome to have a `main.go` file for the elk generator checked in: `./cmd/elk`. It could be improved slightly by accepting some command line argument (for the schema output path, etc.)

**Comment by masseelch** [comment]
`elk` is meant to be run by `go generate` just like Ent is. Having it like this ables us to have the correct version of ent, entc and elk project. 

This setup has only to be done once per project.

Do you have a use case where having a command is useful?

**Comment by lukasmalkmus** [comment]
The setup is just fine. It would be just nice to have the `main.go` file, that is described in the README, checked into the repository. By command I don't mean to provide a binary but rather a `main.go` file at `github.com/masseelch/elk/cmd/elk`, just like `ent` already does. It can still be run using `go run -mod=mod github.com/masseelch/elk/cmd/elk ...` and that command can still go into a `go:generate` statement :) All benefits you described will still apply.

**Comment by lukasmalkmus** [comment]
Actually, it would be super nice if the `ent` team would enhance https://github.com/ent/ent/blob/12227e7ae507bfe79345d4b7f5bfa6c70634ec6a/cmd/internal/base/base.go#L114 is a way that would let package users inject extensions there. So tools like elk could provide their own command that imports the `generate` command but injects their appropriate extension. This would allow for the `generate` command to keep a stable api surface across ent related generators.

Imagine I have this in my `//go:generate` statement: `go run -mod=mod entgo.io/cmd/ent generate --target=./storage ./schema`

To get elk support, I would just replace the `cmd` to run: `go run -mod=mod github.com/masseelch/elk/cmd/elk generate --target=./storage ./schema`

But that be some future talk :)

**Comment by masseelch** [comment]
> [...] It would be just nice to have the `main.go` file, that is described in the README, checked into the repository. [...].

Do you mean the `ent/entc.go`? 

> To get elk support, I would just replace the cmd to run: go run -mod=mod github.com/masseelch/elk/cmd/elk generate --target=./storage ./schema

This would indeed decrease the setup complexity a bit, but this won't work for more than one extension, would it?

**Comment by lukasmalkmus** [comment]
> Do you mean the ent/entc.go?

Yes!

> This would indeed decrease the setup complexity a bit, but this won't work for more than one extension, would it?

That is correct. But it would at least decrease the setup complexity for tools like `elk` or others that build on `ent`.

**Comment by a8m** [comment]
Hey @masseelch and @lukasmalkmus 👋 

Please, feel free to through suggestions on how's the code-generation config API can be improved. One option I considered in the past was to generate an `ent/entc.go` file by default, because this could make it easier for users to switch from the basic `generate.go` version that ent generates to the extension-based version (e.g. `elk` or `entgql`).

**Comment by masseelch** [comment]
Another option might be to remove the cmd entirely and only go with the `entc.go` package. Afterall the `ent` command just wraps the `entc` package. All the other goodies (currently only `ent Init` can be either be an `ent/contrib` or be deprecated.
