### ISSUE TITLE
no OAS-type exists for field.JSON fields

### ISSUE THREAD

**Issue by JamesHovious** [masseelch/elk#18]
Following along with the blog on an existing schema got me these results:

```bash
go generate ./ent/
2021/09/13 09:16:58 running ent codegen: no OAS-type exists for "*[]schema.Source"
exit status 1
ent/generate.go:5: running "go": exit status 1
```

In my schema `Source` is defined as 

```
field.JSON("sources", &[]Source{}).Optional(),
```

Are JSON fields not supported by this plugin? If not what are the chances that they will/could be ?

Latest version of everything (Go, Ent, Elk)

**Comment by masseelch** [comment]
Hey @JamesHovious!

JSON fields are currently not support for the OAS generation but I am already working on it.  My plan is to have this done next week.

**Comment by masseelch** [comment]
Hey @JamesHovious, I have some bad news: Generating a schema for the used type in `field.JSON()` is not as trivial as I thought. 

@a8m Can you be of help here? I currently have no way of getting a `reflection` of the type given to `field.JSON()` and therefore cannot get information about the properties of that type. A current (bad) workaround is putting a JSON type as undefined map into the spec.

**Comment by gedw99** [comment]
maybe this helps ? https://github.com/buger/jsonparser

**Comment by nicolasparada** [comment]
Missing this :(

**Comment by nicolasparada** [comment]
This issue is for entoas, bu it is already fixed in master through usage of annotations.

```go
field.JSON("meta", &[]Source{}).Annotations(entoas.Annotation{
	Schema: ogen.String(),
})
```

**Comment by masseelch** [comment]
> This issue is for entoas, but it is already fixed in master through usage of annotations.
> 
> ```go
> field.JSON("sources", &[]Source{}).Annotations(entoas.Annotation{
> 	Schema: ogen.String().AsArray(), // or something else, dunno.
> })
> ```

You can even go further and create your own schema for the `Source`:

```go
field.JSON("sources", &[]Source{}).Annotations(entoas.Annotation{
	Schema: ogen.NewSchema().
		AddOptionalProperties(
			ogen.String().ToProperty("string"),
			ogen.Int().ToProperty("int"),
		),
})
```
This will improve documentation and codegen capabilities of swagger etc.

**Comment by nicolasparada** [comment]
That's very nice 👌

**Comment by gedw99** [comment]
@masseelch wow that looks like the annotations can describe a json schema at runtime . This means that I can load me schema at runtime. Which then means I can expose it as an API as well as gen my swagger at runtime  ?

this is really sneaky stuff
