### ISSUE TITLE
Consider generating a client?

### ISSUE THREAD

**Issue by AWinterman** [masseelch/elk#19]
It would be really cool to generate a client as well. Thoughts?

**Comment by masseelch** [comment]
Hey @AWinterman!

If you have a look at #2, @gedw is implementing a client / GUI for elk. 

In the meantime you can use the generated OpenAPI spec and generate a client with swagger tooling. Let me know if You need assistance with that. 

The "first" Version of elk had a nearly ready Flutter client. I will eventually update it to the current state but I don't have a timeframe yet.

**Comment by AWinterman** [comment]
Perfect thanks!

**Comment by AWinterman** [comment]
Ah wait, specifically I was looking for a golang http client. I know I can generate one from open api spec, but that's actually more valuable to me than a UI

**Comment by masseelch** [comment]
Got it! Since swagger tooling can generate one for you there currently is no plan to provide a client generator in this package.

**Comment by gedw99** [comment]
I also would like to gen a golang client . 

The gui I am building in golang but a golang client would make it much easier. The gui client can run on web or desktop of mobile.

So if anyway gets the generation of a golang client using openapi it would be helpful

**Comment by AWinterman** [comment]
I just got this set up. I can pr the docs with instructions

**Comment by gedw99** [comment]
Thanks @AWinterman

**Comment by masseelch** [comment]
A PR will be very welcome!

**Comment by AWinterman** [comment]
See https://github.com/masseelch/elk/pull/21
