### ISSUE TITLE
Gui

### ISSUE THREAD

**Issue by gedw99** [masseelch/elk#2]
Gio instead of flutter is my own preference.

used to use flutter and switched to gio which is golang based and is architecturally the same as flutter is how it fundamentally works.

would be easier to support also.

checkout the gio examples !

component is a good starter: https://github.com/gioui/gio-example/tree/main/x/component

**Comment by masseelch** [comment]
I'll have a look at it. Thank you for the suggestion 😊

**Comment by gedw99** [comment]
Gio can compile to Browser, Desktop and Mobile from the same code. Just like flutter.

it’s much easier to debug and extend imho if your already a golang we coder.

in the last month many developers have started to build apps south it and support is stellar I find.

I will be happy to help build the gui for ent. 

The chat app in gio is probably the most advanced and best practice at the moment, so worth looking at that one

**Comment by masseelch** [comment]
I am amazed how well it works :scream:

**Comment by gedw99** [comment]
About the app bundle, your absolutely right that Google has made it mandatory now!

I think it’s worth raising it on their issues on sourcehut and mentioning that it’s for Ent gui. They are eager to have the system used. 

Also adding app bundling is quite easy when you look at the cmd folder. But I think if you raised it it will be added quite quickly.



One guy originated it, true. He is mainly working on the gpu shader acceleration which works well with other working on other bits now.

 I also had the same concerns as you , but there are now 2 or 3 other deep into the team and some are paid by companies to work on it.


So yes it’s a small group compared to the massive Google flutter team.
I tried to use it for a project 8 months ago but decided not too. But am now using it for 2 projects as I can see how support and stability has picked up. The support is really great too and feedback within a day I have noticed.

there will be some rough edges but the core is solid.

**Comment by gedw99** [comment]
Also I just wanted to point out that if you wanted to add something to the flutter core you would have a really hard time.

with gio is so much easier to get things added / fixed, even at the core. Or do fo it yourself and get quick reviews via GitHub.

this I find is one of the highly attractive aspects.

**Comment by gedw99** [comment]
https://github.com/planetdecred/godcr is a good example of a big app btw

**Comment by gedw99** [comment]
@masseelch I raised the issue here about the Google Play Store bundling:
https://todo.sr.ht/~eliasnaur/gio/249

**Comment by gedw99** [comment]
I also found many golang toolng with MIT licenses that does the bundling here:

https://github.com/search?l=&q=bundletool+language%3AGo&type=code

**Comment by gedw99** [comment]
@masseelch I think gio does support bundling ( . aab ) . I just looked into the code, but have not done a deploy to google play store yet myself.

https://github.com/p9c/gio/blob/main/cmd/gogio/androidbuild.go

I will let the Issue in source hut stand to get confirmation though.

**Comment by gedw99** [comment]
@masseelch 

Android app bundling works. I tried it myself.

See:

https://todo.sr.ht/~eliasnaur/gio/249#event-93164

**Comment by gedw99** [comment]
hey @masseelch 

ok, I can work on the GUI for Ent.

Can i get your feedback on the following ?

**HTTP REST versus GraphQL**

Can you outline why a GraphQL version is preferred. I ask so that i understand the tradeoffs and why you asked for it to be this way.  

**GUI side caching**

I would like to eventually add caching to the GUI, and want to get your thoughts on this.  

GUI caching is a useful for the Ent Admin GUI, but for any golang devs building projects using Ent and GIO.  It gives perf, offline support, etc.

One way to do it would be to use genji ( https://github.com/genjidb/genji ) .

Genji can be embedded into GIO because, like GIO, it supports Browser WASM, Desktop and Mobile and is also Golang based. Desktop and Mobile use the badgerDB engine, and Browser WASM uses a memory engine (  IndexedDB is on the roadmap ).
I have been using Genji for about 6 months, and its been ok, but API changes a fair bit still.

The following sequence would be:
- When a mutation is sent from the GIO GUI to the Ent Server, the Ent Server updates the respective View, and then emits a change event using the Outbox pattern. 
- The GUI would get the Change event via a subscription, and update the Genji Table.

I do not know how far the Ent team got on supporting the OutBox pattern, which is probably required to support the sequence. Do you know ?

**Comment by masseelch** [comment]
> HTTP REST versus GraphQL

It is my opinion, that GraphQL will be the standard in the future and will replace REST any time soon. At least for newer APIs. It offers way more flexibility over REST. However, it is totally up to you, what backend you take. Note though, that the`elk` is still in development. 

> GUI side caching

Eventually this is a useful feature. Currently genji has no release though and is considered unstable as is `elk`. I'd say start the work and keep in mind you want to add caching in the future and consider it when designing the API (`middlewares` is what immediatly came to my mind). I do not know about ent OutBox.

**Comment by gedw99** [comment]
ok will use graphql and wait on caching.

Will let you know here how it goes...

**Comment by masseelch** [comment]
Looking forward to it. In the meantime I close this.

**Comment by gedw99** [comment]
Saw the OAS.

this will make it a breeze to gen the golang gui .

I want to integrate push also eventually. For example a record changes in the dB and I want all clients to be send the changes record. I am using SSE and web sockets but I thing SSE will be better for ease of use.

The intent is to make the gui real time such that you see data changes so that collaboration is more complete.

So curious what your options are to do this ?

ent hooks is the way to do this ?

ent privacy can later model auth aspects ?

history catchup can be don’t by using the Outbox pattern where the events are stored in ent ?

**Comment by masseelch** [comment]
Hey @gedw99, sorry to only answer now. I did not get a notification on this issue since it is closed.

I'd prefer SSE too, since it works with http and this will prevent a lot of hassle that comes with using websockets.

I like the real-time idea. Hooks on a mutation are definetly the way to go. Keep in mind though to only notify connected clients when the query was executed succesfully and not when the hook is called.

I am still thinking about providing some options to spec generation to sync privacy and authentication. 

Can you use Outbox pattern with just SSE?

**Comment by gedw99** [comment]
> Can you use Outbox pattern with just SSE?

yes, its just push based on some event queue as a table in the db.

**Comment by gedw99** [comment]
> I am still thinking about providing some options to spec generation to sync privacy and authentication.

i feel this is really important. Groups would need to be modelled and then Users. Auth would be done by external system, and a new Signup would then create the User inside Ent, and get default group. 

The most flexile pattern if for groups to be in groups like a tree.  Then you can effectively have Orgs with their own groups and users inside it. So basically you have a multi tenant solution then.

- Group A (Super Admin )
   - User ID 00 ( the actual Super Admin )
  - Group B ( Org "blah blah")
    - Group C ( role inside this org )
      - User ID 01
      - User ID 02

Then you can run a Server per Org Org, and distribute all Auth meta data ( described above) via NATS. So it's effectively a way to shard the database, but keep it nicely unified in terms of all the auth meta.

NATS is very effective at this role.
