### ISSUE TITLE
Curl add user

### ISSUE THREAD

**Issue by wr125** [masseelch/elk#26]
following instructions on how to add user to db and I'm getting this error. Not sure what I'm doing wrong.
```json
{"level":"error","msg":"could not create profile","handler":"ProfileHandler","method":"Create","error":"ent: missing required field 
\"username\""}
```
Using

```shell
curl -X 'POST' -H 'Content-Type: application/json' -d '{"username":"Elk","email":"elk@gmail.com","password":"Elk123"}' 'localhost:3000/profiles
```

Tried postman, same error. Profile looks like this:

```go
func (Profile) Fields() []ent.Field {
	return []ent.Field{
		field.String("username").
			Immutable(),
		field.String("email").
			Unique(),
		field.String("password").
			Sensitive(),
	}
}
func (Profile) Edges() []ent.Edge {
	return []ent.Edge{
		edge.To("customers", Customer.Type),
		edge.To("suppliers", Supplier.Type),
		edge.To("admins", Admin.Type),
	}
}
```

**Comment by masseelch** [comment]
Does it work without immutable username? If yes, you might have found a bug.

**Comment by wr125** [comment]
doesn't look like it. I removed all methods;
func (Profile) Fields() []ent.Field {
	return []ent.Field{
		field.String("username"),
		field.String("email"),
		field.String("password"),
	}
}
and got
{"level":"error","msg":"could not create profile","handler":"ProfileHandler","method":"Create","error":"ent: missing required field \"username\""}

my server.go file looks like this *mysql)
func main() {
	c, err := ent.Open("mysql", "user:pass@tcp(localhost:3306)/testdb")
	if err != nil {
		log.Fatalf("failed opening connection to sqlite: %v", err)
	}
	defer c.Close()
	// Run the auto migration tool.
	if err := c.Schema.Create(context.Background()); err != nil {
		log.Fatalf("failed creating schema resources: %v", err)
	}

	// Start listen to incoming requests.
	fmt.Println("server is running on port :3000")
	if err := http.ListenAndServe(":3000", elk.NewHandler(c, zap.NewExample())); err != nil {
		log.Fatal(err)
	}
}

**Comment by wr125** [comment]
this is what the handler looks like for profile;

// ProfileHandler handles http crud operations on ent.Profile.
type ProfileHandler struct {
	client *ent.Client
	log    *zap.Logger
}

func NewProfileHandler(c *ent.Client, l *zap.Logger) *ProfileHandler {
	return &ProfileHandler{
		client: c,
		log:    l.With(zap.String("handler", "ProfileHandler")),
	}
}
func (h *ProfileHandler) MountCreateRoute(r chi.Router) *ProfileHandler {
	r.Post("/profiles", h.Create)
	return h
}
func (h *ProfileHandler) MountReadRoute(r chi.Router) *ProfileHandler {
	r.Get("/profiles/{id}", h.Read)
	return h
}
func (h *ProfileHandler) MountUpdateRoute(r chi.Router) *ProfileHandler {
	r.Patch("/profiles/{id}", h.Update)
	return h
}
func (h *ProfileHandler) MountDeleteRoute(r chi.Router) *ProfileHandler {
	r.Delete("/profiles/{id}", h.Delete)
	return h
}
func (h *ProfileHandler) MountListRoute(r chi.Router) *ProfileHandler {
	r.Get("/profiles", h.List)
	return h
}
func (h *ProfileHandler) MountCustomersRoute(r chi.Router) *ProfileHandler {
	r.Get("/profiles/{id}/customers", h.Customers)
	return h
}
func (h *ProfileHandler) MountSuppliersRoute(r chi.Router) *ProfileHandler {
	r.Get("/profiles/{id}/suppliers", h.Suppliers)
	return h
}
func (h *ProfileHandler) MountAdminsRoute(r chi.Router) *ProfileHandler {
	r.Get("/profiles/{id}/admins", h.Admins)
	return h
}
func (h *ProfileHandler) MountRoutes(r chi.Router) {
	h.MountCreateRoute(r).MountReadRoute(r).MountUpdateRoute(r).MountDeleteRoute(r).MountListRoute(r).MountCustomersRoute(r).MountSuppliersRoute(r).MountAdminsRoute(r)
}
Error again
{"level":"error","msg":"could not create profile","handler":"ProfileHandler","method":"Create","error":"ent: missing required field \"username\""} Question, should their be a username field in the post method while there is an error?

**Comment by wr125** [comment]
db table profile
![profile](https://user-images.githubusercontent.com/20228047/134369728-51733374-a30c-4fbc-990a-61a7dd0f8378.png)

**Comment by wr125** [comment]
i will share

**Comment by masseelch** [comment]
Your code regeneration is not working because there was a bug in `elk` when generating schemas with an uuid on a non-ID field. I fixed it in [this commit](https://github.com/masseelch/elk/tree/95ecde28fa723639455a1f25f76ccde174c14315). I added a new tag v0.4.6.

Running this commands in your repo should fix it: 

```shell
go get -u github.com/masseelch/elk@v0.4.6
go generate ./...
```

Sorry for the inconvenience.

**Comment by wr125** [comment]
```
well, when you fix one another one shows up :). I ran the following
go run server.go
server is running on port :3000
2021/09/23 10:00:11 http: panic serving 127.0.0.1:47062: runtime error: invalid memory address or nil pointer dereference
goroutine 152 [running]:
net/http.(*conn).serve.func1()
        /usr/local/go/src/net/http/server.go:1801 +0xb9
panic({0xa84440, 0x1003400})
        /usr/local/go/src/runtime/panic.go:1047 +0x266
github.com/wr125/auction_ent/ent/http.ProfileHandler.Create({0xc000097c70, 0xc00023e0c0}, {0xbf10b0, 0xc000104620}, 0xc000108a00)
        /home/robert/go/src/github.com/wr125/auction_ent/ent/http/create.go:929 +0xdb3
net/http.HandlerFunc.ServeHTTP(0xa81e20, {0xbf10b0, 0xc000104620}, 0xc00020151d)
        /usr/local/go/src/net/http/server.go:2046 +0x2f
github.com/go-chi/chi/v5.(*Mux).routeHTTP(0xc0000abb00, {0xbf10b0, 0xc000104620}, 0xc000108a00)
        /home/robert/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.4/mux.go:442 +0x216
net/http.HandlerFunc.ServeHTTP(0xbf55f8, {0xbf10b0, 0xc000104620}, 0x1003020)
        /usr/local/go/src/net/http/server.go:2046 +0x2f
github.com/go-chi/chi/v5.(*Mux).ServeHTTP(0xc0000abb00, {0xbf10b0, 0xc000104620}, 0xc000108700)
        /home/robert/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.4/mux.go:88 +0x442
net/http.serverHandler.ServeHTTP({0xbf02e8}, {0xbf10b0, 0xc000104620}, 0xc000108700)
        /usr/local/go/src/net/http/server.go:2878 +0x43b
net/http.(*conn).serve(0xc000244aa0, {0xbf56a0, 0xc0002580f0})
        /usr/local/go/src/net/http/server.go:1929 +0xb08
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:3033 +0x4e8
^Csignal: interrupt

I received;
curl -X 'POST' -H 'Content-Type: application/json' -d '{"username":"jack","email":"jack@gmail.com","password":"123"}' 'localhost:3000/profiles'
curl: (52) Empty reply from server

Also, I noticed the port is different from default.

```

**Comment by masseelch** [comment]
I started the server in your repo and everything worked without a hassle:

```shell
curl -X 'POST' -H 'Content-Type: application/json' -d '{"username":"jack","email":"jack@gmail.com","password":"123"}' 'localhost:3000/profiles'
```

```json
{"level":"info","msg":"profile rendered","handler":"ProfileHandler","method":"Create","id":1}
```

**Comment by masseelch** [comment]
Running it on mysql gave me an error. I am investigating.

**Comment by masseelch** [comment]
```shell
go get -u github.com/masseelch/elk@v0.4.7
go generate ./...
```

You keep finding bugs. I am grateful, I can fix them :-)

**Comment by wr125** [comment]
Where differently making good progress here :)

server is running on port :3000
{"level":"error","msg":"could not create profile","handler":"ProfileHandler","method":"Create","error":"ent: constraint failed: Error 1062: Duplicate entry 'jack@gmail.com' for key 'email'"}

{"level":"error","msg":"could not read profile","handler":"ProfileHandler","method":"Create","error":"sql: Scan error on column index 1, name \"create_time\": unsupported Scan, storing driver.Value type []uint8 into type *time.Time","id":3}

{"level":"error","msg":"could not read profile","handler":"ProfileHandler","method":"Create","error":"sql: Scan error on column index 1, name \"create_time\": unsupported Scan, storing driver.Value type []uint8 into type *time.Time","id":4}
^Csignal: interrupt

Input

curl -X 'POST' -H 'Content-Type: application/json' -d '{"username":"jack","email":"jack@gmail.com","password":"123"}' 'localhost:3000/profiles'
{"code":500,"status":"Internal Server Error"}

curl -X 'POST' -H 'ContElk","email":"elk@gmail.com","password":"Elk123"}' 'localhost:3000/profiles'
{"code":500,"status":"Internal Server Error"}

curl -X 'POST' -H 'Controbert","email":"rob@gmail.com","password":"rob231"}' 'localhost:3000/profiles'
{"code":500,"status":"Internal Server Error"}

**Comment by masseelch** [comment]
Please always surround your codeblock with tripple backticks ` ``` ` to format it.

> ```shell
> {"level":"error","msg":"could not create profile","handler":"ProfileHandler","method":"Create","error":"ent: constraint failed: Error 1062: Duplicate entry 'jack@gmail.com' for key 'email'"}

This one is because you have `field.String("email").Unique()` in your schema.

> {"level":"error","msg":"could not read profile","handler":"ProfileHandler","method":"Create","error":"sql: Scan error on column index 1, name \"create_time\": unsupported Scan, storing driver.Value type []uint8 into type *time.Time","id":3}
> {"level":"error","msg":"could not read profile","handler":"ProfileHandler","method":"Create","error":"sql: Scan error on column index 1, name \"create_time\": unsupported Scan, storing driver.Value type []uint8 into type *time.Time","id":4}

You need to put `parseTime=true` in your DSN.

**Comment by wr125** [comment]
ok, lets take things slowly here please :)
1) I see there seems to be an issue the correct formatting (I want duplication check). So this needs to be resolved. How to do this; you say use ``` do I use field.String(```email```).Unique(),? I don't think so, so where in the doc does this example clearly?
2)"You need to put parseTime=true in your DSN" I am using linux mint so do I need to edit a file? And what does this do?

**Comment by wr125** [comment]
```After doing a little digging I think we need to add parseTime=True in the mysql connection? So documentation https://entgo.io/docs/migrate should be changed to ent.Open("mysql", "user:password@tcp(localhost:3306)/testdb?charset=utf8mb4&parseTime=True&loc=Local")
go run server.go
server is running on port :3000
{"level":"info","msg":"profile rendered","handler":"ProfileHandler","method":"Create","id":5}
{"level":"info","msg":"profile rendered","handler":"ProfileHandler","method":"Create","id":6}
{"level":"info","msg":"profile rendered","handler":"ProfileHandler","method":"Create","id":7}
Input
curl -X 'POST' -H 'Contpat","email":"pat@gmail.com","password":"pat543"}' 'localhost:3000/profiles'
{"id":5,"create_time":"2021-09-23T12:49:25+01:00","update_time":"2021-09-23T12:49:25+01:00","username":"pat","email":"pat@gmail.com"}

curl -X 'POST' sally","email":"sally@gmail.com","password":"sally32"}' 'localhost:3000/profiles'
{"id":6,"create_time":"2021-09-23T12:50:21+01:00","update_time":"2021-09-23T12:50:21+01:00","username":"sally","email":"sally@gmail.com"}

curl -X 'POsimon","email":"simon@gmail.com","password":"simon12"}' 'localhost:3000/profiles'
{"id":7,"create_time":"2021-09-23T12:51:14+01:00","update_time":"2021-09-23T12:51:14+01:00","username":"simon","email":"simon@gmail.com"}```

**Comment by masseelch** [comment]
The string where you provide the credentials to connect to the database is called DSN. Putting parse `time=True` as I mentioned and you did is only requires, when you use datetime columns.

**Comment by wr125** [comment]
I edited the credit_card field to look like this edge.To("creditcard", CreditCard.Type) and reran the code
go generate ./...
2021/09/23 14:50:09 running ent codegen: entc/gen: resolve "CardType" relations: edge "card_type" is missing for inverse edge: CardType.credit_card(CreditCard)
exit status 1
ent/generate.go:3: running "go": exit status 1 

I want to use the below hook on the creditcard but ent can't find ent.CreditCardMutation. Do I also need the second hook?
```
func (CreditCard) Hooks() []ent.Hook {
	return []ent.Hook{
		// First hook.
		hook.On(
			func(next ent.Mutator) ent.Mutator {
				return hook.CreditCardFunc(func(ctx context.Context, m *ent.CreditCardMutation) (ent.Value, error) {
					if num, ok := m.Number(); ok && len(num) < 10 {
						return nil, fmt.Errorf("card number is too short")
					}
					return next.Mutate(ctx, m)
				})
			},
			// Limit the hook only for these operations.
			ent.OpCreate|ent.OpUpdate|ent.OpUpdateOne,
		),
		// Second hook.
		func(next ent.Mutator) ent.Mutator {
			return ent.MutateFunc(func(ctx context.Context, m ent.Mutation) (ent.Value, error) {
				if s, ok := m.(interface{ SetName(string) }); ok {
					s.SetName("Boring")
				}
				return next.Mutate(ctx, m)
			})
		},
	}
```

**Comment by wr125** [comment]
Manged to complie the code because I edited the card_type node. However, I still get CreditCardMutation not declared by package on m *ent.CreditCardMutation. What am I missing?

**Comment by masseelch** [comment]
This are questions regarding Ent and not elk. So please ask them in either slack or discord. You will find help there (mine for example) 😊

**Comment by wr125** [comment]
Think there might be another issue or something, as I've added Positive(), method to a field and is showing an error in http/update.go file. Removed it and it goes away. Issue also with Username which I do have but saying its undefined in the update file. I've pushed the repository to github so you can do a pull request on it and let us know.
