### ISSUE TITLE
Update Error Message / HTTP Folder

### ISSUE THREAD

**Issue by wr125** [masseelch/elk#27]
Think there might be another issue or something, as I've added Positive(), method to a field and is showing an error in http/update.go file. Removed it and it goes away. Issue also with Username which I do have but saying its undefined in the update file. I've pushed the repository to github so you can do a pull request on it and let us know.

**Comment by masseelch** [comment]
I'll have a look. Is it the `copy` branch?

**Comment by masseelch** [comment]
That branch does not exist. Please provide a reproducible example, so I can have a look.

**Comment by wr125** [comment]
you can use the second branch copy.

**Comment by masseelch** [comment]
Please update elk to `v0.4.8`.

**Comment by wr125** [comment]
Receiving validation error on SetEmail
go run server.go
```shell
2021/09/28 13:33:42 failed adding user details to database: ent: validator failed for field "email": please enter a valid email address
```
```go
func User(ctx context.Context, client *ent.Client) error {
	if err := client.User.CreateBulk(
		client.User.Create().SetUsername("pauline").SetPassword("paul834").SetEmail("pauline@gmail.com"),
		client.User.Create().SetUsername("patrick").SetPassword("patrick214").SetEmail("patick@gmail.com"),
		client.User.Create().SetUsername("jason").SetPassword("jason001").SetEmail("jason@gmail.com"),
		client.User.Create().SetUsername("anna").SetPassword("anna125").SetEmail("anna@gmail.com"),
		client.User.Create().SetUsername("Jack").SetPassword("jackson43").SetEmail("jackson@gmail.com"),

		// ...
	).Exec(ctx); err != nil {
		return err
	}
```
validate
```go
field.String("email").Unique().
			Match(regexp.MustCompile("^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*$")).
			Validate(func(s string) error {
				if s == s {
					return errors.New("please enter a valid email address")
				}
				return nil
			}),
```

**Comment by wr125** [comment]
forgot to add; if s != s

**Comment by masseelch** [comment]
This is not an error with elk. Please refrain from using the GitHub Issues for questions regarding Ent. That is what the Slack and Discord channels are for. 

You mean this Validator?
```go
Validate(func(s string) error {
	if s != s {
		return errors.New("please enter a valid email address")
	}
	return nil
})
```
That will always return nil. For literally every string there is. If swapped to `if s == s ` it will always fail. https://play.golang.org/p/Mlme54tfutN
