### ISSUE TITLE
How do you deal with sanitization?

### ISSUE THREAD

**Issue by idc77** [masseelch/elk#37]
Let's take some Post that has a content text field.

The client can pass html or markdown
You can't trust this input and it needs to be sanitized, with https://github.com/microcosm-cc/bluemonday for instance.

What options are available, short of manually modifying the generated http dir?

Is this in scope of elk or should this be handled by ent?

**Comment by masseelch** [comment]
Hey @idc77, thanks for reaching out. Ent is meant to be the place where you out all your business logic. Elk is just generating the (dumb) rpc layer. 

Sanitizing strings can be done with a [mutation hook](https://entgo.io/docs/hooks#mutation).

**Comment by idc77** [comment]
Thanks for your response @masseelch , appreciate it.

For anyone wondering and stumbling upon this by accident

```go
package schema

import (
	"context"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/schema/edge"
	"entgo.io/ent/schema/field"
	gen "<package name>/ent"
	"<package name>/ent/hook"
	"github.com/microcosm-cc/bluemonday"
)

// Post holds the schema definition for the Post entity.
type Post struct {
	ent.Schema
}

// Fields of the Post.
func (Post) Fields() []ent.Field {
	return []ent.Field{
		field.Int64("id"),
		field.Time("created_at").Default(time.Now),
		field.Time("updated_at").
			Default(time.Now).
			UpdateDefault(time.Now).
			Optional().
			Nillable(),
		field.String("subject_id"),
		field.String("username"),
		field.Text("content_raw"),
	}
}

// Edges of the Post.
func (Post) Edges() []ent.Edge {
	return []ent.Edge{
		edge.To("comments", Comment.Type),
	}
}

func (Post) Hooks() []ent.Hook {
	return []ent.Hook{
		hook.On(
			func(next ent.Mutator) ent.Mutator {
				return hook.PostFunc(
					func(ctx context.Context, m *gen.PostMutation) (gen.Value, error) {
						if s, ok := m.ContentRaw(); ok {
							p := bluemonday.UGCPolicy()
							m.SetContentRaw(p.Sanitize(s))
						}
						return next.Mutate(ctx, m)
					},
				)
			},
			ent.OpCreate|ent.OpUpdate|ent.OpUpdateOne,
		),
	}
}
```

**Comment by gedw99** [comment]
https://github.com/a8m/ent-sync-example

Also uses hooks and shows how to use blobs with ent .
