### ISSUE TITLE
Open api async ?

### ISSUE THREAD

**Issue by gedw99** [masseelch/elk#39]
There are now golang reps that provide open api that works with standard http request / response but also asynchronous situations too. 

Async can be anything you want . Emit an emit when some record collection changes in your db. Useful for clients to stay up to date. 

It makes for an alternative to graphql subscriptions . 

If you want some URLs of golang repos that implement open api async let me know . 

If would be cool to be able to use ent this way

**Comment by masseelch** [comment]
Hey @gedw99, if you have I'd really like to see those :-=

**Comment by gedw99** [comment]
https://github.com/orgs/asyncapi/repositories?q=&type=&language=go&sort=
