### ISSUE TITLE
Generated code did not import github.com/masseelch/render 

### ISSUE THREAD

**Issue by imperiutx** [masseelch/elk#4]
Hi, I just did the same as your guide here: https://entgo.io/blog/2021/07/29/generate-a-fully-working-go-crud-http-api-with-ent/. 
But when I did the step: Next, start the server: go run -mod=mod main.go

I found out that some generated go files in elk-example/ent/http: create.go, delete.go, read.go, update.go, list.go did not import github.com/masseelch/render so after typing above command, it returned errors: 

ent/http/create.go:28:3: undefined: render
ent/http/create.go:42:3: undefined: render
ent/http/create.go:53:4: undefined: render
ent/http/create.go:56:4: undefined: render
ent/http/create.go:60:12: undefined: sheriff
ent/http/create.go:66:3: undefined: render
ent/http/create.go:70:2: undefined: render
ent/http/create.go:84:3: undefined: render
ent/http/create.go:92:3: undefined: render
ent/http/create.go:103:4: undefined: render
ent/http/create.go:103:4: too many errors

Can you fix this one? or did I miss something?

**Comment by masseelch** [comment]
Hey @imperiutx, thank you for reaching out and reporting this. 

Can you please show me the contents of your `go.mod` file? 

Does `goimports -w .` add the missing imports?

**Comment by imperiutx** [comment]
The contents of go.mod file:

module elk-example

go 1.16

require (
	entgo.io/ent v0.8.1-0.20210720072308-756517e559eb
	github.com/go-chi/chi/v5 v5.0.3
	github.com/go-playground/validator/v10 v10.7.0
	github.com/leodido/go-urn v1.2.1 // indirect
	github.com/lib/pq v1.10.2
	go.uber.org/atomic v1.8.0 // indirect
	go.uber.org/multierr v1.7.0 // indirect
	go.uber.org/zap v1.18.1
	golang.org/x/crypto v0.0.0-20210616213533-5ff15b29337e // indirect
	golang.org/x/sys v0.0.0-20210630005230-0f9fa26af87c // indirect
	golang.org/x/text v0.3.6 // indirect
)

I tried to install goimports but it returned: 
go imports -w .
go imports: unknown command

**Comment by masseelch** [comment]
The correct command is `goimports` instead of `go imports`. Note the missing space.

**Comment by imperiutx** [comment]
I'm sorry, my bad. After re-run the commands below, the errors are still there:
go generate ./...                         
go: finding module for package github.com/masseelch/elk
go: found github.com/masseelch/elk in github.com/masseelch/elk v0.2.2
➜  elk-example goimports -w .         
➜  elk-example go run -mod=mod main.go
# elk-example/ent/http
ent/http/create.go:28:3: undefined: render
ent/http/create.go:42:3: undefined: render
ent/http/create.go:53:4: undefined: render
ent/http/create.go:56:4: undefined: render
ent/http/create.go:60:12: undefined: sheriff
ent/http/create.go:66:3: undefined: render
ent/http/create.go:70:2: undefined: render
ent/http/create.go:84:3: undefined: render
ent/http/create.go:92:3: undefined: render
ent/http/create.go:103:4: undefined: render
ent/http/create.go:103:4: too many errors

**Comment by masseelch** [comment]
Weird :thinking: I'll look into it. Sorry for the inconvenience!

**Comment by masseelch** [comment]
Can you run:

```shell
go get -u github.com/masseelch/render 
go get -u github.com/liip/sheriff
goimports -w .
go run -mod=mod main.go
```

I will set up a clean GO_ENV this evening and try to reproduce the issue. Might have something to with cached packages by `go get`.

**Comment by imperiutx** [comment]
After running the above commands, server is running. Thank you for your support

**Comment by masseelch** [comment]
Glad i could help. I will update the post. Thank you again for reporting this!
