### ISSUE TITLE
no OAS-type exists for "[]byte"

### ISSUE THREAD

**Issue by nicolasparada** [masseelch/elk#43]
When using:
```go
field.Bytes("someBytes")
```

**Comment by nicolasparada** [comment]
Oh, this is fixed on master in entoas.

**Comment by masseelch** [comment]
Hey @nicolasparada, yes it is :-) 
Ans I can share with you, that an implementation for the `entoas` spec is in the pipeline. Should'nt take much longer to the first release :-)

**Comment by nicolasparada** [comment]
Awesome 👏
