### ISSUE TITLE
responseView function not getting passed correct annotations from template for Serialization Groups

### ISSUE THREAD

**Issue by SteveCastle** [masseelch/elk#7]
The issue I am having is when generating response types (in list, read, create etc), the `responseView` function is not getting passed any groups from the template and hashing to the wrong type name, so none of my API endpoints with group annotations return the right fields.

I haven't quite figured out how to fix this, but maybe you would know right away.

On the following line, I believe that the annotation name should be `ElkSchema` instead of `Elk`, but for some reason when I make that change it doesn't seem to work either.  I may be missing or misunderstanding something about how this works.

https://github.com/masseelch/elk/blob/521494bc0bbb898a6b9c433503dadc43ddd7e30e/template/http/read.tmpl#L34

**Comment by masseelch** [comment]
Hey @SteveCastle, thank you for reporting this. 

I have a look later today, but you are on the right track.

**Comment by masseelch** [comment]
If you changed it, you have to rebuild the `go-bindata` contents by running `go generate` [here](https://github.com/masseelch/elk/blob/master/template.go). I think you've might forgot that step after the change.
